### ISSUE TITLE
How to add structurizr file in specific folder?

### ISSUE THREAD

**Issue by junaidahmed92** [structurizr/dotnet-core-quickstart#1]
By default structurizr creates files in same directory as of program.cs and that is really annoying. So is there anyway to create structurizr files in specific folder?

**Comment by simonbrowndotje** [comment]
Which files are you referring to?

**Comment by junaidahmed92** [comment]
Structurizr creates new file on each build. I am taking about those files

**Comment by simonbrowndotje** [comment]
I still don’t understand which files you are referring to. Do you have an example file name?

**Comment by junaidahmed92** [comment]
Sorry for late reply, the example file name is
"structurizr-37626-20180905134622.json". Each time I run the project it
adds the new file in same directory like this

**Comment by simonbrowndotje** [comment]
You can change this behaviour by setting the ```WorkspaceArchiveLocation``` property. See https://github.com/structurizr/dotnet/blob/master/docs/api-client.md#1-getworkspace for more details.

**Comment by junaidahmed92** [comment]
Thanks alot, One more thing, I can't figure out how to give current folder
path in DirectoryInfo(). I want to add files in a new folder say
"StructurizrFiles" which is in same assembly as that of Structurizr.cs class
